# Optional overrides for Kubernetes resource names.
nameOverride: ""
fullnameOverride: ""

# We use one Kanboard replica because the application volumes
# currently use EBS ReadWriteOnce storage.
replicaCount: 1

image:
  repository: monishs2722/kanboard-cicd

  # Argo CD or values-production.yaml will provide the
  # immutable SHA image tag.
  tag: ""

  pullPolicy: IfNotPresent

application:
  debug: "false"

  # Keep installation of plugins through the web interface disabled.
  pluginInstaller: "false"

service:
  type: ClusterIP
  port: 80
  targetPort: http

resources:
  requests:
    cpu: 200m
    memory: 256Mi

  limits:
    cpu: "1"
    memory: 1Gi

persistence:
  # This StorageClass will be created when EBS CSI is configured.
  storageClassName: gp3-encrypted-retain

  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi

  plugins:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi

postgres:
  enabled: true

  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent

  database: kanboard
  username: kanboard

  # The chart does not create this Secret.
  # It will be supplied securely during deployment.
  existingSecret: postgres-secret

  # Key used by the PostgreSQL container.
  passwordKey: postgres-password

  # Key used by the Kanboard Deployment.
  databaseUrlKey: database-url

  service:
    port: 5432

  persistence:
    enabled: true
    storageClassName: gp3-encrypted-retain
    accessMode: ReadWriteOnce
    size: 10Gi

  terminationGracePeriodSeconds: 60

  podSecurityContext: {}

  containerSecurityContext:
    allowPrivilegeEscalation: false

  resources:
    requests:
      cpu: 250m
      memory: 512Mi

    limits:
      cpu: "1"
      memory: 1Gi

gateway:
  enabled: true
  className: eg
  name: kanboard-gateway

  listener:
    name: http
    protocol: HTTP
    port: 80

httpRoute:
  enabled: true
  hostname: app.kubeace.in

tls:
  enabled: false
  clusterIssuer: letsencrypt-staging
  secretName: app-kubeace-in-tls
  redirectHTTPToHTTPS: false
