{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: {{ required "gateway.name must be configured" .Values.gateway.name }}

  labels:
    {{- include "kanboard.labels" . | nindent 4 }}

spec:
  gatewayClassName: {{ required "gateway.className must be configured" .Values.gateway.className }}

  listeners:
    - name: {{ required "gateway.listener.name must be configured" .Values.gateway.listener.name }}

      protocol: {{ required "gateway.listener.protocol must be configured" .Values.gateway.listener.protocol }}

      port: {{ required "gateway.listener.port must be configured" .Values.gateway.listener.port }}

      hostname: {{ required "httpRoute.hostname must be configured" .Values.httpRoute.hostname | quote }}

      allowedRoutes:
        namespaces:
          from: Same

        kinds:
          - group: gateway.networking.k8s.io
            kind: HTTPRoute
{{- end }}
