{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "kanboard.dataPvcName" . }}

  labels:
    {{- include "kanboard.labels" . | nindent 4 }}

spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}

  storageClassName: {{ .Values.persistence.storageClassName | quote }}

  volumeMode: Filesystem

  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
