{{- if .Values.persistence.plugins.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ required "persistence.plugins.claimName is required" .Values.persistence.plugins.claimName }}

  labels:
    {{- include "kanboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugins-storage

spec:
  accessModes:
    {{- toYaml .Values.persistence.plugins.accessModes | nindent 4 }}

  storageClassName: {{ required "persistence.plugins.storageClass is required" .Values.persistence.plugins.storageClass | quote }}

  resources:
    requests:
      storage: {{ .Values.persistence.plugins.size }}
{{- end }}
